//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ВПФки
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.ProOrd = new HashSet<ProOrd>();
            this.ProWare = new HashSet<ProWare>();
        }
    
        public int IDprod { get; set; }
        public string Name { get; set; }
        public string Descr { get; set; }
        public Nullable<int> IDcateg { get; set; }
        public int IDsup { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public decimal Price { get; set; }
        public int IDunit { get; set; }
        public byte[] Image { get; set; }
    
        public int Quantity { get; set; }


        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProOrd> ProOrd { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProWare> ProWare { get; set; }
        public virtual Units Units { get; set; }
        public virtual Suppliers Suppliers { get; set; }
    }
}
