//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ВПФки
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProOrd
    {
        public int ID { get; set; }
        public int IDprod { get; set; }
        public int IDord { get; set; }
        public int AmountOrd { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
