//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ВПФки
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserExtraData
    {
        public int IDuser { get; set; }
        public string Phone { get; set; }
        public string Mail { get; set; }
    
        public virtual User User { get; set; }
    }
}
